{{- if .Values.serviceMonitor.enabled }}
{{- range $component := list "server" "worker" }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "commerce.name" $ }}-{{ $component }}
  labels:
    {{- include "commerce.labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "commerce.selector" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $component }}
  podMetricsEndpoints:
    - port: admin
      path: /metrics
      interval: 30s
{{- end }}
{{- end }}
